version: '2'
services:
 tomcatdata:
    build:
      context: .
      dockerfile: application.Dockerfile
    container_name: application
 tomcatrunner:
    build:
      context: .
      dockerfile: tomcat.Dockerfile
    depends_on: [ "tomcatdata" ]
    volumes_from: [ "tomcatdata" ]
    container_name: tomcat
 nginxrunner:
    build:
      context: .
      dockerfile: web.Dockerfile
    links:
     - tomcatrunner
    depends_on: 
     - tomcatrunner
     - tomcatdata
    expose: [ "80" ]
    ports: [ "0.0.0.0:8080:80" ]
    container_name: nginx
