version: '2'
services:
 application:
    build:
      context: .
      dockerfile: application.Dockerfile
 tomcat:
    build:
      context: .
      dockerfile: tomcat.Dockerfile
    depends_on: [ "application" ]
    volumes_from: [ "application" ]
    expose: [ "8080" ]
 nginx:
    build:
      context: .
      dockerfile: web.Dockerfile
    depends_on: [ "tomcat" ]
    expose: [ "80" ]   
    ports: [ "0.0.0.0:8080:80" ]