version: '2'
services:
  app:
    build:
      context: .
      dockerfile: application/application.Dockerfile
    command: sleep infinity
  tomcat:
    build:
      context: .
      dockerfile: tomcat/tomcat.Dockerfile
    depends_on: [ "app" ]
    volumes_from: [ "app" ]
  web:
    build:
      context: .
      dockerfile: web/web.Dockerfile
    ports: [ "8080:80" ]
